import type { Metadata } from "next";
import { montserrat } from "@/app/ui/fonts";
import "./globals.css";
import TopNav from "@/app/ui/nav/topnav";

export const metadata: Metadata = {
  title: "Diagnost_46",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"\${montserrat.className} min-h-screen"}>
        <div className="flex flex-col items-center m-auto max-w-[1240px]">
          <TopNav />
        </div>
        <main className="flex-col m-auto max-w-[1240px]">{children}</main>
      </body>
    </html>
  );
}
